name: Build & Push Medusa App Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # --- Backend ---
      - name: Build Medusa Backend Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-medusa-store ./my-medusa-store

      - name: Push Medusa Backend Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-medusa-store

      # --- Storefront ---
      - name: Build Medusa Storefront Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/my-medusa-store-storefront ./my-medusa-store-storefront

      - name: Push Medusa Storefront Image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/my-medusa-store-storefront
