name: Build & Push Medusa App Images

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY: docker.io
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}

      # --- Backend ---
      - name: Build Medusa Backend Image
        run: |
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/my-medusa-store ./my-medusa-store

      - name: Push Medusa Backend Image
        run: |
          docker push ${{ env.DOCKERHUB_USERNAME }}/my-medusa-store

      # --- Storefront ---
      - name: Build Medusa Storefront Image
        run: |
          docker build -t ${{ env.DOCKERHUB_USERNAME }}/my-medusa-store-storefront ./my-medusa-store-storefront

      - name: Push Medusa Storefront Image
        run: |
          docker push ${{ env.DOCKERHUB_USERNAME }}/my-medusa-store-storefront
